=== medizininformatik-initiative/torch/DEQ/deq_draft_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "string",
        "format": "uri",
        "description": "Version identifier with a reference to a schema definition."
      },
      "display": {
        "type": "string",
        "description": "A display string."
      },
      "cohortDefinition": {
        "$ref": "clinical-cohort-definition-language-schema.json",
        "description": "Reference to a cohort definition in CCDL schemas."
      },
      "dataExtraction": {
        "type": "object",
        "properties": {
          "attributeGroups": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "groupReference": {
                  "type": "string",
                  "description": "Reference to a resource group, e.g., an ID or a resource URL."
                },
                "attributes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "attributeRef": {
                        "type": "string",
                        "description": "Unique reference to an attribute; mapping required."
                      },
                      "mustHave": {
                        "type": "boolean",
                        "description": "Indicates whether the attribute is essential in the resource."
                      }
                    },
                    "required": ["attributeRef", "mustHave"],
                    "description": "List of attributes, with reference and necessity indicated."
                  }
                },
                "filter": {
                  "$ref": "clinical-cohort-definition-language-schema.json",
                  "description": "Reference to filter definitions in CCDL schemas."
                }
              },
              "required": ["groupReference", "attributes"]
            }
          }
        }
      }
    },
    "required": ["version", "cohortDefinition", "dataExtraction"]
  }

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_it-kds-vitalstatus-crtdl.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "111bea",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Vitalstatus",
        "attributes": [
          {
            "attributeRef": "Observation.id",
            "mustHave": true
          },
          {
            "attributeRef": "Observation.value[x]",
            "mustHave": false
          }
        ]
      },
      {
        "id": "111-pat",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.id",
            "mustHave": true
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/torch-app/src/test/resources/ReferenceResolveBlackBoxIT/crtdl-with-two-substance-filters.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgewählte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "med-group",
        "name": "Medication",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication",
        "attributes": [
          {
            "attributeRef": "Medication.code",
            "mustHave": false
          },
          {
            "attributeRef": "Medication.manufacturer",
            "mustHave": false,
            "linkedGroups": [
              "linked-orga-group"
            ]
          },
          {
            "attributeRef": "Medication.ingredient.item[x]",
            "mustHave": false,
            "linkedGroups": [
              "subst-group-1",
              "subst-group-2"
            ]
          }
        ]
      },
      {
        "id": "linked-orga-group",
        "name": "Organization",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Organization",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Organization.name",
            "mustHave": false
          }
        ]
      },
      {
        "id": "med-adm-group",
        "name": "MedicationAdministration",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration",
        "attributes": [
          {
            "attributeRef": "MedicationAdministration.medication[x]",
            "mustHave": false,
            "linkedGroups": [
              "med-group"
            ]
          }
        ]
      },
      {
        "id": "subst-group-1",
        "name": "Substance",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Substance",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Substance.code",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://fhir.de/CodeSystem/bfarm/atc",
                "code": "N06AA25"
              }
            ]
          }
        ]
      },
      {
        "id": "subst-group-2",
        "name": "Substance",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Substance",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Substance.code",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://fhir.de/CodeSystem/bfarm/atc",
                "code": "N06A"
              }
            ]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_enc-period.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgew√§hlte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.active",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.deceased[x]",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "enc-1-diab-enc",
        "name": "Diabetes Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.status",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.class",
            "mustHave": false
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CRTDL/CRTDL_diagnosis_basic_consent.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "context": {
            "code": "Einwilligung",
            "display": "Einwilligung",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "termCodes": [
            {
              "code": "yes-yes-no-yes",
              "display": "Verteilte, EU-DSGVO konforme Analyse, ohne Krankenassendaten, und mit Rekontaktierung",
              "system": "fdpg.consent.combined"
            }
          ]
        },
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "diagnosis basic",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          }
        ]
      },
      {
        "id": "Patient",
        "includeReferenceOnly": true,
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
        ],
        "filter": [
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_diag-enc-diag.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgewählte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "diag-1-diab",
        "name": "Diabetes Diagnosis (Main Diagnosis)",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.subject",
            "mustHave": true,
            "linkedGroups": ["pat-1-main"]
          },
          {
            "attributeRef": "Condition.encounter",
            "mustHave": true,
            "linkedGroups": ["enc-1-diab-enc"]
          },
          {
            "attributeRef": "Condition.clinicalStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.verificationStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.recordedDate",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "E13.0",
                "display": "Sonstiger näher bezeichneter Diabetes mellitus: Mit Koma",
                "system": "http://fhir.de/CodeSystem/bfarm/icd-10-gm",
                "version": "2099"
              }
            ]
          }
        ]
      },
      {
        "id": "diag-2-other-diab-enc-diagnoses",
        "name": "Other Diagnoses for Diab Enc",
        "includeReferenceOnly": true,
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.subject",
            "mustHave": true,
            "linkedGroups": ["pat-1-main"]
          },
          {
            "attributeRef": "Condition.encounter",
            "mustHave": false,
            "linkedGroups": ["enc-1-diab-enc"]
          },
          {
            "attributeRef": "Condition.clinicalStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.verificationStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.recordedDate",
            "mustHave": false
          }
        ]
      },
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.active",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.deceased[x]",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "enc-1-diab-enc",
        "name": "Diabetes Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.subject",
            "mustHave": true,
            "linkedGroups": ["pat-1-main"]
          },
          {
            "attributeRef": "Encounter.status",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.class",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.diagnosis.condition",
            "mustHave": false,
            "linkedGroups": ["diag-2-other-diab-enc-diagnoses"]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/ReferenceResolveBlackBoxIT/crtdl-without-encounter-filter.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgew√§hlte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "enc-group-1",
        "name": "Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "includeReferenceOnly": true,
        "attributes": [
            {
            "attributeRef": "Encounter.period",
            "mustHave": true
            }
        ]
      },
      {
        "id": "enc-group-2",
        "name": "Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Encounter.period",
            "mustHave": true
          }
        ]
      },
      {
        "id": "obs-group-1",
        "name": "Observation",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.focus",
            "mustHave": false,
            "linkedGroups": ["enc-group-1"]
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": ["enc-group-2"]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_diag-diag-profile-double.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgew√§hlte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "diag-1",
        "name": "Diagnosis primary ",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-onko/StructureDefinition/mii-pr-onko-diagnose-primaertumor",
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          }
        ]
      },
      {
        "id": "diag-1",
        "name": "Diagnosis primary ",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          }
        ]
      },
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.active",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.deceased[x]",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/DirectLoadBlackBoxIT/CRTDL_ref-not-found.json
{
    "display": "",
    "version": "http://json-schema.org/to-be-done/schema#",
    "cohortDefinition": {
        "version": "http://to_be_decided.com/draft-1/schema#",
        "display": "Ausgewählte Merkmale",
        "inclusionCriteria": [
            [
                {
                    "termCodes": [
                        {
                            "code": "263495000",
                            "display": "Geschlecht",
                            "system": "http://snomed.info/sct",
                            "version": ""
                        }
                    ],
                    "context": {
                        "code": "Patient",
                        "display": "Patient",
                        "system": "fdpg.mii.cds",
                        "version": "1.0.0"
                    },
                    "valueFilter": {
                        "selectedConcepts": [
                            {
                                "code": "male",
                                "display": "Male",
                                "system": "http://hl7.org/fhir/administrative-gender",
                                "version": "2099"
                            },
                            {
                                "code": "female",
                                "display": "Female",
                                "system": "http://hl7.org/fhir/administrative-gender",
                                "version": "2099"
                            }
                        ],
                        "type": "concept"
                    }
                }
            ]
        ]
    },
    "dataExtraction": {
        "attributeGroups": [
            {
                "id": "pat",
                "name": "standard pat",
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
                "attributes": [
                    {
                        "attributeRef": "Patient.active",
                        "mustHave": false
                    },
                    {
                        "attributeRef": "Patient.birthDate",
                        "mustHave": false
                    }
                ]
            },
            {
                "id": "med-group",
                "name": "Medication",
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication",
                "attributes": [
                    {
                        "attributeRef": "Medication.manufacturer",
                        "mustHave": false,
                        "linkedGroups": [
                            "orga-group"
                        ]
                    }
                ]
            },
            {
                "id": "orga-group",
                "name": "Organization",
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Organization",
                "attributes": [
                    {
                        "attributeRef": "Organization.name",
                        "mustHave": false
                    }
                ]
            }
        ]
    }
}
