=== medizininformatik-initiative/torch/DEQ/deq_draft_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "string",
        "format": "uri",
        "description": "Version identifier with a reference to a schema definition."
      },
      "display": {
        "type": "string",
        "description": "A display string."
      },
      "cohortDefinition": {
        "$ref": "clinical-cohort-definition-language-schema.json",
        "description": "Reference to a cohort definition in CCDL schemas."
      },
      "dataExtraction": {
        "type": "object",
        "properties": {
          "attributeGroups": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "groupReference": {
                  "type": "string",
                  "description": "Reference to a resource group, e.g., an ID or a resource URL."
                },
                "attributes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "attributeRef": {
                        "type": "string",
                        "description": "Unique reference to an attribute; mapping required."
                      },
                      "mustHave": {
                        "type": "boolean",
                        "description": "Indicates whether the attribute is essential in the resource."
                      }
                    },
                    "required": ["attributeRef", "mustHave"],
                    "description": "List of attributes, with reference and necessity indicated."
                  }
                },
                "filter": {
                  "$ref": "clinical-cohort-definition-language-schema.json",
                  "description": "Reference to filter definitions in CCDL schemas."
                }
              },
              "required": ["groupReference", "attributes"]
            }
          }
        }
      }
    },
    "required": ["version", "cohortDefinition", "dataExtraction"]
  }

=== medizininformatik-initiative/torch/torch-app/src/test/resources/CRTDL/CRTDL_medication_must_have.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "424144002",
              "system": "http://snomed.info/sct",
              "display": "Gegenwärtiges chronologisches Alter"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "type": "quantity-comparator",
            "unit": {
              "code": "a",
              "display": "a"
            },
            "value": 18,
            "comparator": "gt"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "8-918",
              "system": "http://fhir.de/CodeSystem/bfarm/ops",
              "version": "2023",
              "display": "Interdisziplinäre multimodale Schmerztherapie"
            }
          ],
          "context": {
            "code": "Procedure",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Prozedur"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "Medication",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/ext/modul-biobank/StructureDefinition/Organization",
        "attributes": [
          {
            "attributeRef": "Organization.name",
            "mustHave": true
          }
        ],
        "filter": []
      },
      {
        "id": "Patient",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
        ],
        "filter": [
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/torch-app/src/test/resources/ReferenceResolveBlackBoxIT/crtdl-with-two-condition-filters.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgewählte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "cond-group-1",
        "name": "Main Cond for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://snomed.info/sct",
                "code": "39065001"
              }
            ]
          }
        ]
      },
      {
        "id": "cond-group-2",
        "name": "Main Cond for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://snomed.info/sct",
                "code": "262581006"
              }
            ]
          }
        ]
      },
      {
        "id": "enc-group",
        "name": "Main Enc for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.diagnosis.condition",
            "mustHave": false,
            "linkedGroups": [
              "cond-group-1",
              "cond-group-2"
            ]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/DEQ/deq_example1.json
{
  "version": "http://to_be_decided.com/draft-1/schema#",
  "display": "Elderly Diabetes Patients",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Patients above 65 with diabetes",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "424144002",
              "system": "http://snomed.info/sct",
              "display": "Current chronological age"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "type": "quantity-comparator",
            "unit": {
              "code": "a",
              "display": "years"
            },
            "value": 65,
            "comparator": "gt"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "44054006",
              "system": "http://snomed.info/sct",
              "display": "Diabetes mellitus"
            }
          ],
          "context": {
            "code": "Diagnosis",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Diagnosis"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "groupReference": "Medication",
        "attributes": [
          {
            "attributeRef": "medicationCode",
            "mustHave": true
          },
          {
            "attributeRef": "dosage",
            "mustHave": true
          }
        ],
        "filter": [
          [
            {
              "termCodes": [
                {
                  "code": "A10",
                  "system": "http://fhir.de/CodeSystem/bfarm/atc",
                  "version": "2022",
                  "display": "Drugs used in diabetes"
                }
              ],
              "context": {
                "code": "Medication",
                "system": "fdpg.mii.cds",
                "version": "1.0.0",
                "display": "Medication"
              }
            }
          ]
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CRTDL/CRTDL_patient.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.identifier",
            "mustHave": false
          }
        ],
        "filter": [
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CRTDL/CRTDL_MedicationAdministraion_linked_encounter_linked_medication.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "1234",
        "name": "Observation",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.encounter",
            "mustHave": true,
            "linkedGroups": [
              "Encounter1"
            ]
          }
        ],
        "filter": [
        ]
      },
      {
        "id": "Observation2",
        "name": "Observation2",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.encounter",
            "mustHave": true,
            "linkedGroups": [
              "Encounter1"
            ]
          }
        ],
        "filter": []
      },
      {
        "id": "Encounter1",
        "name": "Encounter",
        "includeReferenceOnly": true,
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.id",
            "mustHave": false
          }
        ]
      },
      {
        "id": "MedicationAdministration1",
        "name": "MedicationAdministrationToEcounterAndMedication",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration",
        "attributes": [
          {
            "attributeRef": "MedicationAdministration.context",
            "mustHave": true,
            "linkedGroups": [
              "Encounter1"
            ]
          },
          {
            "attributeRef": "MedicationAdministration.medication[x]",
            "mustHave": true,
            "linkedGroups": [
              "Medication1"
            ]
          }
        ]
      },
      {
        "id": "Medication1",
        "name": "Medication1",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Medication.code",
            "mustHave": true
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_it-kds-perf-crtdl.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "patient",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.id",
            "mustHave": true
          }
        ]
      },
      {
        "id": "diagnosis",
        "name": "Diagnosis",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.clinicalStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.verificationStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.recordedDate",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://fhir.de/CodeSystem/bfarm/icd-10-gm",
                "code": "B05.3",
                "version": "2023"
              }
            ]
          }
        ]
      },
      {
        "id": "encounter",
        "name": "Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.status",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.class",
            "mustHave": false
          }
        ]
      },
      {
        "id": "leukocytes",
        "name": "Leukocytes",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "26464-8",
                "system": "http://loinc.org",
                "display": "Leukocytes [#/volume] in Blood"
              }
            ]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/it-kds-crtdl.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "111bea",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.subject",
            "mustHave": true,
            "linkedGroups": ["111-pat"]
          }
        ]
      },
      {
        "id": "111-pat",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/Patient",
        "attributes": [
          {
            "attributeRef": "Patient.id",
            "mustHave": true
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CRTDL/CRTDL_observation_linked_encounter.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "1234",
        "name": "Observation",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.encounter",
            "mustHave": true,
            "linkedGroups": [
              "985"
            ]
          }
        ],
        "filter": []
      },
      {
        "id": "Observation2",
        "name": "Observation2",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.id",
            "mustHave": false
          }
        ],
        "filter": []
      },
      {
        "id": "985",
        "name": "Encounter",
        "includeReferenceOnly": true,
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
        ]
      }
    ]
  }
}
