=== medizininformatik-initiative/torch/DEQ/deq_draft_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "version": {
        "type": "string",
        "format": "uri",
        "description": "Version identifier with a reference to a schema definition."
      },
      "display": {
        "type": "string",
        "description": "A display string."
      },
      "cohortDefinition": {
        "$ref": "clinical-cohort-definition-language-schema.json",
        "description": "Reference to a cohort definition in CCDL schemas."
      },
      "dataExtraction": {
        "type": "object",
        "properties": {
          "attributeGroups": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "groupReference": {
                  "type": "string",
                  "description": "Reference to a resource group, e.g., an ID or a resource URL."
                },
                "attributes": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "attributeRef": {
                        "type": "string",
                        "description": "Unique reference to an attribute; mapping required."
                      },
                      "mustHave": {
                        "type": "boolean",
                        "description": "Indicates whether the attribute is essential in the resource."
                      }
                    },
                    "required": ["attributeRef", "mustHave"],
                    "description": "List of attributes, with reference and necessity indicated."
                  }
                },
                "filter": {
                  "$ref": "clinical-cohort-definition-language-schema.json",
                  "description": "Reference to filter definitions in CCDL schemas."
                }
              },
              "required": ["groupReference", "attributes"]
            }
          }
        }
      }
    },
    "required": ["version", "cohortDefinition", "dataExtraction"]
  }

=== medizininformatik-initiative/torch/src/test/resources/ReferenceResolveBlackBoxIT/crtdl-without-practitioner-filter.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgew√§hlte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "prac-group-1",
        "name": "PractitionerRole",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-beteiligte-person",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "PractitionerRole.period",
            "mustHave": true
          }
        ]
      },
      {
        "id": "prac-group-2",
        "name": "PractitionerRole",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/modul-studie/StructureDefinition/mii-pr-studie-beteiligte-person",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "PractitionerRole.period",
            "mustHave": true
          }
        ]
      },
      {
        "id": "med-req-group-1",
        "name": "MedicationRequest",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest",
        "attributes": [
          {
            "attributeRef": "MedicationRequest.recorder",
            "mustHave": false,
            "linkedGroups": ["prac-group-1"]
          },
          {
            "attributeRef": "MedicationRequest.requester",
            "mustHave": false,
            "linkedGroups": ["prac-group-2"]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/torch-app/src/test/resources/CrtdlItTests/CRTDL_test_it-kds-perf-w-ref.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "patient",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": []
      },
      {
        "id": "diagnosis",
        "name": "Diagnosis",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.clinicalStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.verificationStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.recordedDate",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "system": "http://fhir.de/CodeSystem/bfarm/icd-10-gm",
                "code": "B05"
              }
            ]
          }
        ]
      },
      {
        "id": "encounter",
        "name": "Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Encounter.status",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.class",
            "mustHave": false
          }
        ]
      },
      {
        "id": "leukocytes",
        "name": "Leukocytes",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": [
              "encounter"
            ]
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "26464-8",
                "system": "http://loinc.org",
                "display": "Leukocytes [#/volume] in Blood"
              }
            ]
          }
        ]
      },
      {
        "id": "erythrocytes",
        "name": "Erythrocytes",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": [
              "encounter"
            ]
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "26453-1",
                "system": "http://loinc.org",
                "display": "Erythrocytes [#/volume] in Blood"
              }
            ]
          }
        ]
      },
      {
        "id": "hematocrit",
        "name": "Hematocrit",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": [
              "encounter"
            ]
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "20570-8",
                "system": "http://loinc.org",
                "display": "Hematocrit [Volume Fraction] of Blood"
              }
            ]
          }
        ]
      },
      {
        "id": "hemoglobin",
        "name": "Hemoglobin",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": [
              "encounter"
            ]
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "718-7",
                "system": "http://loinc.org",
                "display": "Hemoglobin [Mass/volume] in Blood"
              }
            ]
          }
        ]
      },
      {
        "id": "platelets",
        "name": "Platelets",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.category",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.code",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.encounter",
            "mustHave": false,
            "linkedGroups": [
              "encounter"
            ]
          },
          {
            "attributeRef": "Observation.interpretation",
            "mustHave": false
          },
          {
            "attributeRef": "Observation.value[x]:valueQuantity",
            "mustHave": false
          }
        ],
        "filter": [
          {
            "type": "token",
            "name": "code",
            "codes": [
              {
                "code": "26515-7",
                "system": "http://loinc.org",
                "display": "Platelets [#/volume] in Blood"
              }
            ]
          }
        ]
      },
      {
        "id": "medication-request",
        "name": "MedicationRequest",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationRequest",
        "attributes": [
          {
            "attributeRef": "MedicationRequest.medication[x]:medicationReference",
            "mustHave": true,
            "linkedGroups": [
              "medication"
            ]
          },
          {
            "attributeRef": "MedicationRequest.encounter",
            "mustHave": true,
            "linkedGroups": [
              "encounter"
            ]
          }
        ]
      },
      {
        "id": "medication",
        "name": "Medication",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/Medication",
        "includeReferenceOnly": true,
        "attributes": [
          {
            "attributeRef": "Medication.code",
            "mustHave": true
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_consent-ext.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgewählte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "2.16.840.1.113883.3.1937.777.24.5.3.8",
              "display": "MDAT wissenschaftlich nutzen EU DSGVO NIVEAU",
              "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
              "version": "1.0.7"
            }
          ],
          "context": {
            "code": "Einwilligung",
            "display": "Einwilligung",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "2.16.840.1.113883.3.1937.777.24.5.3.6",
              "display": "MDAT erheben",
              "system": "urn:oid:2.16.840.1.113883.3.1937.777.24.5.3",
              "version": "1.0.7"
            }
          ],
          "context": {
            "code": "Einwilligung",
            "display": "Einwilligung",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "male",
                "display": "Male",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "other",
                "display": "Other",
                "system": "http://hl7.org/fhir/administrative-gender"
              },
              {
                "code": "unknown",
                "display": "Unknown",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "attributes": [
          {
            "attributeRef": "Patient.active",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.gender",
            "mustHave": true
          },
          {
            "attributeRef": "Patient.birthDate",
            "mustHave": true
          }
        ],
        "id": "6abd6380-c1ad-4ac0-aa98-fe40a58437f1",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "name": "MII PR Person Patient (Pseudonymisiert)"
      },
      {
        "attributes": [
          {
            "attributeRef": "Consent.category",
            "mustHave": false
          },
          {
            "attributeRef": "Consent.dateTime",
            "mustHave": false
          },
          {
            "attributeRef": "Consent.policy",
            "mustHave": false
          },
          {
            "attributeRef": "Consent.provision",
            "mustHave": false
          },
          {
            "attributeRef": "Consent.status",
            "mustHave": false
          }
        ],
        "id": "605c5b82-8403-44c0-98b3-182fd7d4e825",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/modul-consent/StructureDefinition/mii-pr-consent-einwilligung",
        "name": "Profile - MI-I - Consent - Einwilligung"
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/DirectLoadBlackBoxIT/CRTDL_must-have.json
{
    "display": "",
    "version": "http://json-schema.org/to-be-done/schema#",
    "cohortDefinition": {
        "version": "http://to_be_decided.com/draft-1/schema#",
        "display": "Ausgewählte Merkmale",
        "inclusionCriteria": [
            [
                {
                    "termCodes": [
                        {
                            "code": "263495000",
                            "display": "Geschlecht",
                            "system": "http://snomed.info/sct",
                            "version": ""
                        }
                    ],
                    "context": {
                        "code": "Patient",
                        "display": "Patient",
                        "system": "fdpg.mii.cds",
                        "version": "1.0.0"
                    },
                    "valueFilter": {
                        "selectedConcepts": [
                            {
                                "code": "male",
                                "display": "Male",
                                "system": "http://hl7.org/fhir/administrative-gender",
                                "version": "2099"
                            },
                            {
                                "code": "female",
                                "display": "Female",
                                "system": "http://hl7.org/fhir/administrative-gender",
                                "version": "2099"
                            }
                        ],
                        "type": "concept"
                    }
                }
            ]
        ]
    },
    "dataExtraction": {
        "attributeGroups": [
            {
                "id": "pat",
                "name": "standard pat",
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
                "attributes": [
                    {
                        "attributeRef": "Patient.active",
                        "mustHave": false
                    },
                    {
                        "attributeRef": "Patient.birthDate",
                        "mustHave": false
                    }
                ]
            },
            {
                "id": "med-adm-group",
                "name": "MedicationAdministration",
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-medikation/StructureDefinition/MedicationAdministration",
                "attributes": [
                    {
                        "attributeRef": "MedicationAdministration.subject",
                        "mustHave": false
                    },
                    {
                        "attributeRef": "MedicationAdministration.partOf",
                        "mustHave": true,
                        "linkedGroups": ["proc-group"]
                    }
                ]
            },
            {
                "id": "proc-group",
                "name": "Procedure",
                "includeReferenceOnly": true,
                "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-prozedur/StructureDefinition/Procedure",
                "attributes": [
                    {
                        "attributeRef": "Procedure.subject",
                        "mustHave": false
                    },
                    {
                        "attributeRef": "Procedure.status",
                        "mustHave": true
                    }
                ]
            }
        ]
    }
}

=== medizininformatik-initiative/torch/src/test/resources/CrtdlItTests/CRTDL_test_diag-enc-diag-ref-backbone.json
{
  "display": "",
  "version": "http://json-schema.org/to-be-done/schema#",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "Ausgew√§hlte Merkmale",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "display": "Geschlecht",
              "system": "http://snomed.info/sct",
              "version": ""
            }
          ],
          "context": {
            "code": "Patient",
            "display": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender",
                "version": "2099"
              }
            ],
            "type": "concept"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "diag",
        "name": "Diabetes Diagnosis (Main Diagnosis)",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-diagnose/StructureDefinition/Diagnose",
        "attributes": [
          {
            "attributeRef": "Condition.clinicalStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.verificationStatus",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.code",
            "mustHave": false
          },
          {
            "attributeRef": "Condition.recordedDate",
            "mustHave": false
          }
        ]
      },
      {
        "id": "pat-1-main",
        "name": "Main Pat for Extraction",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-person/StructureDefinition/PatientPseudonymisiert",
        "attributes": [
          {
            "attributeRef": "Patient.active",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.deceased[x]",
            "mustHave": false
          },
          {
            "attributeRef": "Patient.gender",
            "mustHave": false
          }
        ]
      },
      {
        "id": "enc-1-diab-enc",
        "name": "Diabetes Encounter",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-fall/StructureDefinition/KontaktGesundheitseinrichtung",
        "attributes": [
          {
            "attributeRef": "Encounter.status",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.class",
            "mustHave": false
          },
          {
            "attributeRef": "Encounter.diagnosis",
            "mustHave": false,
            "linkedGroups": [
              "diag"
            ]
          }
        ]
      }
    ]
  }
}

=== medizininformatik-initiative/torch/src/test/resources/CRTDL/CRTDL_observation_not_contained.json
{
  "version": "http://json-schema.org/to-be-done/schema#",
  "display": "",
  "cohortDefinition": {
    "version": "http://to_be_decided.com/draft-1/schema#",
    "display": "",
    "inclusionCriteria": [
      [
        {
          "termCodes": [
            {
              "code": "424144002",
              "system": "http://snomed.info/sct",
              "display": "Gegenwärtiges chronologisches Alter"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "type": "quantity-comparator",
            "unit": {
              "code": "a",
              "display": "a"
            },
            "value": 1,
            "comparator": "le"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "263495000",
              "system": "http://snomed.info/sct",
              "display": "Geschlecht"
            }
          ],
          "context": {
            "code": "Patient",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Patient"
          },
          "valueFilter": {
            "selectedConcepts": [
              {
                "code": "female",
                "display": "Female",
                "system": "http://hl7.org/fhir/administrative-gender"
              }
            ],
            "type": "concept"
          }
        }
      ],
      [
        {
          "termCodes": [
            {
              "code": "8-918",
              "system": "http://fhir.de/CodeSystem/bfarm/ops",
              "version": "2023",
              "display": "Interdisziplinäre multimodale Schmerztherapie"
            }
          ],
          "context": {
            "code": "Procedure",
            "system": "fdpg.mii.cds",
            "version": "1.0.0",
            "display": "Prozedur"
          }
        }
      ]
    ]
  },
  "dataExtraction": {
    "attributeGroups": [
      {
        "id": "ObservationNotContained",
        "groupReference": "https://www.medizininformatik-initiative.de/fhir/core/modul-labor/StructureDefinition/ObservationLab",
        "attributes": [
          {
            "attributeRef": "Observation.code",
            "mustHave": true
          },
          {
            "attributeRef": "Observation.value[x]",
            "mustHave": true
          }
        ],
        "filter": []
      }
    ]
  }
}
